site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'drinks'
    label: 'Drinks'
    folder: 'content/drinks'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    # editor:
    #   preview: true
    fields:
       - {
          label: 'Drink category',
          name: 'category',
          default: 'bitter',
          options: [{ label: 'Bitter', value: 'bitter' }, { label: 'Sweet', value: 'sweet' }],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Ingredients', name: 'body', widget: 'markdown', required: false }
      - { label: 'Infos', name: 'info', widget: 'markdown', required: false }
  - name: 'food'
    label: 'Food'
    folder: 'content/food'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - {
          label: 'Meal category',
          name: 'category',
          default: 'main',
          options: [{ label: 'Main Dish', value: 'main' }, { label: 'Side Dish', value: 'side' }],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Ingredients', name: 'body', widget: 'markdown', required: false }
      - { label: 'Infos', name: 'info', widget: 'markdown', required: false }
